version: '3'

services:
  web:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: web
    restart: always
    expose:
      - "3000"
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000